### ISSUE TITLE
Take snapshot with MASAR

### ISSUE THREAD

**Issue by shengb** [frib-high-level-controls/save-set-restore#18]
It reports when I use a "test" beamline
"""
Error taking a snapshot for 'test'.
Error sending request to masar service. Timeout occurred.
"""

No other error message available.

**Comment by jbobnar** [comment]
The client uses a timeout when talking to the masar service. The default value is 3 seconds (it is configurable via CS-Studio preferences). For some reason a timeout occurred when the request was sent to masar. Nothing else is known about the service. The timeout could occur because the service was unreachable or it took too long to respond.

**Comment by jbobnar** [comment]
I think I found a reason for the timeout and it is related to the reconnect issue. Whenever there is a request "error", the RPC channel becomes unusable and has to be closed and reopened. It seems like it is a java pvaccess bug. I'll make the same workaround as I did for reconnection.

**Comment by jbobnar** [comment]
2fbad49 should solve at least some (if not all) of the timeout issues.
