### ISSUE TITLE
snapshot event time stamp

### ISSUE THREAD

**Issue by shengb** [frib-high-level-controls/save-set-restore#22]
After taking a snapshot, the time stamp for the event has 4 hours offset from current local time.
![screen shot 2016-03-15 at 2 40 01 pm](https://cloud.githubusercontent.com/assets/3741779/13789831/2520a3ec-eabc-11e5-820c-495cb75f6e99.png)
As shown in above picture, the left hand side is in the CS-Studio, and the right hand shows proper local time.

**Comment by jbobnar** [comment]
This is a timezone difference issue. It's been fixed: c701457

When I saw the formatted date I assumed it is in current timezone, but is in fact formatted to GMT+0. Is there a reason, why masar returns the snapshot times as formatted date string and not as seconds past epoch like it does for the value timestamps? TI think that would be more intuitive, because it is independent of the timezone.
